/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as ClubRouteImport } from './routes/club'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as PlaySlugRouteImport } from './routes/play.$slug'
import { Route as MissionEmotionsCrosswordRouteImport } from './routes/mission.emotions-crossword'
import { Route as ClubJoinCodeRouteImport } from './routes/club.join.$code'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const PlaySlugRoute = PlaySlugRouteImport.update({
  id: '/play/$slug',
  path: '/play/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionEmotionsCrosswordRoute =
  MissionEmotionsCrosswordRouteImport.update({
    id: '/mission/emotions-crossword',
    path: '/mission/emotions-crossword',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClubJoinCodeRoute = ClubJoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => ClubRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/club': typeof ClubRouteWithChildren
  '/journey': typeof JourneyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/studio': typeof StudioRoute
  '/mission/emotions-crossword': typeof MissionEmotionsCrosswordRoute
  '/play/$slug': typeof PlaySlugRoute
  '/profile/edit': typeof ProfileEditRoute
  '/club/join/$code': typeof ClubJoinCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/club': typeof ClubRouteWithChildren
  '/journey': typeof JourneyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/studio': typeof StudioRoute
  '/mission/emotions-crossword': typeof MissionEmotionsCrosswordRoute
  '/play/$slug': typeof PlaySlugRoute
  '/profile/edit': typeof ProfileEditRoute
  '/club/join/$code': typeof ClubJoinCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/club': typeof ClubRouteWithChildren
  '/journey': typeof JourneyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/studio': typeof StudioRoute
  '/mission/emotions-crossword': typeof MissionEmotionsCrosswordRoute
  '/play/$slug': typeof PlaySlugRoute
  '/profile/edit': typeof ProfileEditRoute
  '/club/join/$code': typeof ClubJoinCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/club'
    | '/journey'
    | '/profile'
    | '/studio'
    | '/mission/emotions-crossword'
    | '/play/$slug'
    | '/profile/edit'
    | '/club/join/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/club'
    | '/journey'
    | '/profile'
    | '/studio'
    | '/mission/emotions-crossword'
    | '/play/$slug'
    | '/profile/edit'
    | '/club/join/$code'
  id:
    | '__root__'
    | '/'
    | '/club'
    | '/journey'
    | '/profile'
    | '/studio'
    | '/mission/emotions-crossword'
    | '/play/$slug'
    | '/profile/edit'
    | '/club/join/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClubRoute: typeof ClubRouteWithChildren
  JourneyRoute: typeof JourneyRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  StudioRoute: typeof StudioRoute
  MissionEmotionsCrosswordRoute: typeof MissionEmotionsCrosswordRoute
  PlaySlugRoute: typeof PlaySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/play/$slug': {
      id: '/play/$slug'
      path: '/play/$slug'
      fullPath: '/play/$slug'
      preLoaderRoute: typeof PlaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission/emotions-crossword': {
      id: '/mission/emotions-crossword'
      path: '/mission/emotions-crossword'
      fullPath: '/mission/emotions-crossword'
      preLoaderRoute: typeof MissionEmotionsCrosswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/join/$code': {
      id: '/club/join/$code'
      path: '/join/$code'
      fullPath: '/club/join/$code'
      preLoaderRoute: typeof ClubJoinCodeRouteImport
      parentRoute: typeof ClubRoute
    }
  }
}

interface ClubRouteChildren {
  ClubJoinCodeRoute: typeof ClubJoinCodeRoute
}

const ClubRouteChildren: ClubRouteChildren = {
  ClubJoinCodeRoute: ClubJoinCodeRoute,
}

const ClubRouteWithChildren = ClubRoute._addFileChildren(ClubRouteChildren)

interface ProfileRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClubRoute: ClubRouteWithChildren,
  JourneyRoute: JourneyRoute,
  ProfileRoute: ProfileRouteWithChildren,
  StudioRoute: StudioRoute,
  MissionEmotionsCrosswordRoute: MissionEmotionsCrosswordRoute,
  PlaySlugRoute: PlaySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
