/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as ClubRouteImport } from './routes/club'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as PlaySlugRouteImport } from './routes/play.$slug'
import { Route as MissionReactionRaceRouteImport } from './routes/mission.reaction-race'
import { Route as MissionMoodMatchRouteImport } from './routes/mission.mood-match'
import { Route as MissionEmpathyRelayRouteImport } from './routes/mission.empathy-relay'
import { Route as MissionEmotionsQuizRouteImport } from './routes/mission.emotions-quiz'
import { Route as MissionEmotionsQuickfireRouteImport } from './routes/mission.emotions-quickfire'
import { Route as MissionEmotionsCrosswordRouteImport } from './routes/mission.emotions-crossword'
import { Route as MissionEmotionsCatcherRouteImport } from './routes/mission.emotions-catcher'
import { Route as MissionEmotionDuelRouteImport } from './routes/mission.emotion-duel'
import { Route as ClubJoinCodeRouteImport } from './routes/club.join.$code'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const PlaySlugRoute = PlaySlugRouteImport.update({
  id: '/play/$slug',
  path: '/play/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionReactionRaceRoute = MissionReactionRaceRouteImport.update({
  id: '/mission/reaction-race',
  path: '/mission/reaction-race',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionMoodMatchRoute = MissionMoodMatchRouteImport.update({
  id: '/mission/mood-match',
  path: '/mission/mood-match',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionEmpathyRelayRoute = MissionEmpathyRelayRouteImport.update({
  id: '/mission/empathy-relay',
  path: '/mission/empathy-relay',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionEmotionsQuizRoute = MissionEmotionsQuizRouteImport.update({
  id: '/mission/emotions-quiz',
  path: '/mission/emotions-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionEmotionsQuickfireRoute =
  MissionEmotionsQuickfireRouteImport.update({
    id: '/mission/emotions-quickfire',
    path: '/mission/emotions-quickfire',
    getParentRoute: () => rootRouteImport,
  } as any)
const MissionEmotionsCrosswordRoute =
  MissionEmotionsCrosswordRouteImport.update({
    id: '/mission/emotions-crossword',
    path: '/mission/emotions-crossword',
    getParentRoute: () => rootRouteImport,
  } as any)
const MissionEmotionsCatcherRoute = MissionEmotionsCatcherRouteImport.update({
  id: '/mission/emotions-catcher',
  path: '/mission/emotions-catcher',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionEmotionDuelRoute = MissionEmotionDuelRouteImport.update({
  id: '/mission/emotion-duel',
  path: '/mission/emotion-duel',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubJoinCodeRoute = ClubJoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => ClubRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/club': typeof ClubRouteWithChildren
  '/journey': typeof JourneyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/shop': typeof ShopRoute
  '/studio': typeof StudioRoute
  '/mission/emotion-duel': typeof MissionEmotionDuelRoute
  '/mission/emotions-catcher': typeof MissionEmotionsCatcherRoute
  '/mission/emotions-crossword': typeof MissionEmotionsCrosswordRoute
  '/mission/emotions-quickfire': typeof MissionEmotionsQuickfireRoute
  '/mission/emotions-quiz': typeof MissionEmotionsQuizRoute
  '/mission/empathy-relay': typeof MissionEmpathyRelayRoute
  '/mission/mood-match': typeof MissionMoodMatchRoute
  '/mission/reaction-race': typeof MissionReactionRaceRoute
  '/play/$slug': typeof PlaySlugRoute
  '/profile/edit': typeof ProfileEditRoute
  '/club/join/$code': typeof ClubJoinCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/club': typeof ClubRouteWithChildren
  '/journey': typeof JourneyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/shop': typeof ShopRoute
  '/studio': typeof StudioRoute
  '/mission/emotion-duel': typeof MissionEmotionDuelRoute
  '/mission/emotions-catcher': typeof MissionEmotionsCatcherRoute
  '/mission/emotions-crossword': typeof MissionEmotionsCrosswordRoute
  '/mission/emotions-quickfire': typeof MissionEmotionsQuickfireRoute
  '/mission/emotions-quiz': typeof MissionEmotionsQuizRoute
  '/mission/empathy-relay': typeof MissionEmpathyRelayRoute
  '/mission/mood-match': typeof MissionMoodMatchRoute
  '/mission/reaction-race': typeof MissionReactionRaceRoute
  '/play/$slug': typeof PlaySlugRoute
  '/profile/edit': typeof ProfileEditRoute
  '/club/join/$code': typeof ClubJoinCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/club': typeof ClubRouteWithChildren
  '/journey': typeof JourneyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/shop': typeof ShopRoute
  '/studio': typeof StudioRoute
  '/mission/emotion-duel': typeof MissionEmotionDuelRoute
  '/mission/emotions-catcher': typeof MissionEmotionsCatcherRoute
  '/mission/emotions-crossword': typeof MissionEmotionsCrosswordRoute
  '/mission/emotions-quickfire': typeof MissionEmotionsQuickfireRoute
  '/mission/emotions-quiz': typeof MissionEmotionsQuizRoute
  '/mission/empathy-relay': typeof MissionEmpathyRelayRoute
  '/mission/mood-match': typeof MissionMoodMatchRoute
  '/mission/reaction-race': typeof MissionReactionRaceRoute
  '/play/$slug': typeof PlaySlugRoute
  '/profile/edit': typeof ProfileEditRoute
  '/club/join/$code': typeof ClubJoinCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/club'
    | '/journey'
    | '/profile'
    | '/shop'
    | '/studio'
    | '/mission/emotion-duel'
    | '/mission/emotions-catcher'
    | '/mission/emotions-crossword'
    | '/mission/emotions-quickfire'
    | '/mission/emotions-quiz'
    | '/mission/empathy-relay'
    | '/mission/mood-match'
    | '/mission/reaction-race'
    | '/play/$slug'
    | '/profile/edit'
    | '/club/join/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/club'
    | '/journey'
    | '/profile'
    | '/shop'
    | '/studio'
    | '/mission/emotion-duel'
    | '/mission/emotions-catcher'
    | '/mission/emotions-crossword'
    | '/mission/emotions-quickfire'
    | '/mission/emotions-quiz'
    | '/mission/empathy-relay'
    | '/mission/mood-match'
    | '/mission/reaction-race'
    | '/play/$slug'
    | '/profile/edit'
    | '/club/join/$code'
  id:
    | '__root__'
    | '/'
    | '/club'
    | '/journey'
    | '/profile'
    | '/shop'
    | '/studio'
    | '/mission/emotion-duel'
    | '/mission/emotions-catcher'
    | '/mission/emotions-crossword'
    | '/mission/emotions-quickfire'
    | '/mission/emotions-quiz'
    | '/mission/empathy-relay'
    | '/mission/mood-match'
    | '/mission/reaction-race'
    | '/play/$slug'
    | '/profile/edit'
    | '/club/join/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClubRoute: typeof ClubRouteWithChildren
  JourneyRoute: typeof JourneyRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ShopRoute: typeof ShopRoute
  StudioRoute: typeof StudioRoute
  MissionEmotionDuelRoute: typeof MissionEmotionDuelRoute
  MissionEmotionsCatcherRoute: typeof MissionEmotionsCatcherRoute
  MissionEmotionsCrosswordRoute: typeof MissionEmotionsCrosswordRoute
  MissionEmotionsQuickfireRoute: typeof MissionEmotionsQuickfireRoute
  MissionEmotionsQuizRoute: typeof MissionEmotionsQuizRoute
  MissionEmpathyRelayRoute: typeof MissionEmpathyRelayRoute
  MissionMoodMatchRoute: typeof MissionMoodMatchRoute
  MissionReactionRaceRoute: typeof MissionReactionRaceRoute
  PlaySlugRoute: typeof PlaySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/play/$slug': {
      id: '/play/$slug'
      path: '/play/$slug'
      fullPath: '/play/$slug'
      preLoaderRoute: typeof PlaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission/reaction-race': {
      id: '/mission/reaction-race'
      path: '/mission/reaction-race'
      fullPath: '/mission/reaction-race'
      preLoaderRoute: typeof MissionReactionRaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission/mood-match': {
      id: '/mission/mood-match'
      path: '/mission/mood-match'
      fullPath: '/mission/mood-match'
      preLoaderRoute: typeof MissionMoodMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission/empathy-relay': {
      id: '/mission/empathy-relay'
      path: '/mission/empathy-relay'
      fullPath: '/mission/empathy-relay'
      preLoaderRoute: typeof MissionEmpathyRelayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission/emotions-quiz': {
      id: '/mission/emotions-quiz'
      path: '/mission/emotions-quiz'
      fullPath: '/mission/emotions-quiz'
      preLoaderRoute: typeof MissionEmotionsQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission/emotions-quickfire': {
      id: '/mission/emotions-quickfire'
      path: '/mission/emotions-quickfire'
      fullPath: '/mission/emotions-quickfire'
      preLoaderRoute: typeof MissionEmotionsQuickfireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission/emotions-crossword': {
      id: '/mission/emotions-crossword'
      path: '/mission/emotions-crossword'
      fullPath: '/mission/emotions-crossword'
      preLoaderRoute: typeof MissionEmotionsCrosswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission/emotions-catcher': {
      id: '/mission/emotions-catcher'
      path: '/mission/emotions-catcher'
      fullPath: '/mission/emotions-catcher'
      preLoaderRoute: typeof MissionEmotionsCatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission/emotion-duel': {
      id: '/mission/emotion-duel'
      path: '/mission/emotion-duel'
      fullPath: '/mission/emotion-duel'
      preLoaderRoute: typeof MissionEmotionDuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/join/$code': {
      id: '/club/join/$code'
      path: '/join/$code'
      fullPath: '/club/join/$code'
      preLoaderRoute: typeof ClubJoinCodeRouteImport
      parentRoute: typeof ClubRoute
    }
  }
}

interface ClubRouteChildren {
  ClubJoinCodeRoute: typeof ClubJoinCodeRoute
}

const ClubRouteChildren: ClubRouteChildren = {
  ClubJoinCodeRoute: ClubJoinCodeRoute,
}

const ClubRouteWithChildren = ClubRoute._addFileChildren(ClubRouteChildren)

interface ProfileRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClubRoute: ClubRouteWithChildren,
  JourneyRoute: JourneyRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ShopRoute: ShopRoute,
  StudioRoute: StudioRoute,
  MissionEmotionDuelRoute: MissionEmotionDuelRoute,
  MissionEmotionsCatcherRoute: MissionEmotionsCatcherRoute,
  MissionEmotionsCrosswordRoute: MissionEmotionsCrosswordRoute,
  MissionEmotionsQuickfireRoute: MissionEmotionsQuickfireRoute,
  MissionEmotionsQuizRoute: MissionEmotionsQuizRoute,
  MissionEmpathyRelayRoute: MissionEmpathyRelayRoute,
  MissionMoodMatchRoute: MissionMoodMatchRoute,
  MissionReactionRaceRoute: MissionReactionRaceRoute,
  PlaySlugRoute: PlaySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
